In [1]:
import numpy as np


In [2]:
np

<module 'numpy' from '/Users/yunho/opt/anaconda3/lib/python3.8/site-packages/numpy/__init__.py'>

In [3]:
array1 = np.array([1, 2, 3])

In [4]:
array1


array([1, 2, 3])

In [5]:
type(array1)

numpy.ndarray

In [6]:
array1.shape

(3,)

In [7]:
array2 = np.array([[1, 2, 3], [2, 3, 4]])

In [8]:
type(array2)

numpy.ndarray

In [9]:
shape(array2)

NameError: name 'shape' is not defined

In [10]:
array2.shape

(2, 3)

In [11]:
array1.ndim

1

In [12]:
array2.ndim

2

In [13]:
array1.dtype


dtype('int64')

In [14]:
array3 = np.array([1, 2, 3.0])

In [15]:
array3

array([1., 2., 3.])

In [16]:
array3.dtype

dtype('float64')

In [17]:
array_int = np.array([1, 2, 3])

In [18]:
array_float = array_int.astype('float64')

In [19]:
array_float

array([1., 2., 3.])

In [20]:
array_int


array([1, 2, 3])

In [21]:
sequence_array = np.arrange(10)

AttributeError: module 'numpy' has no attribute 'arrange'

In [22]:
sequence_array = np.arange(10)

In [23]:
sequence_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
sequence_array[3]

3

In [25]:
zero_array = np.zeros((3, 2))

In [26]:
zero_array

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [27]:
zero_array = np.zeros((3, 2), dtype = 'int64')

In [28]:
zero_array

array([[0, 0],
       [0, 0],
       [0, 0]])

In [29]:
one_array = np.ones((3, 2))

In [30]:
one_array

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [31]:
one_array = np.ones((3, 2), dtype = 'int64')

In [32]:
one_array.dtype

dtype('int64')

In [33]:
one_array.shape

(3, 2)

In [34]:
array1 = np.arange(10)

In [35]:
array1.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [36]:
array1.reshape(1, 10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [37]:
array1.reshape(1, 1, 1, 10)

array([[[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]]])

In [38]:
array1.reshape(10, 1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [39]:
array1.reshape(-1, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [40]:
array1 = np.arange(8)

In [41]:
array3d = array1.reshape(2, 2, 2)

In [42]:
array3d

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [43]:
array3d.tolist()

[[[0, 1], [2, 3]], [[4, 5], [6, 7]]]

In [44]:
array5 = array3d.reshape(-1, 1)

In [45]:
array5


array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7]])

In [46]:
array6 = array3d.reshape(1)

ValueError: cannot reshape array of size 8 into shape (1,)

In [47]:
array6 = array3d.reshape(-1)

In [48]:
array6

array([0, 1, 2, 3, 4, 5, 6, 7])

In [49]:
array6 = array3d.reshape(-1, 1)

In [50]:
array1d = np.arange(start = 1, stop = 10)

In [51]:
array1d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
array3d = array1d.reshape(3, 3)

In [53]:
array3d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
array3d[0, 0]

1

In [55]:
array3d[0][0]

1

In [56]:
array3d[1, 0]

4

In [57]:
array3d[2, 0]

7

In [58]:
import time



In [59]:
a


NameError: name 'a' is not defined

In [60]:
time.now()

AttributeError: module 'time' has no attribute 'now'

In [61]:
time.strftime('%c', time.localtime(time.time()))

'Sat May 29 10:38:49 2021'

In [62]:
#breaktime

In [63]:
array1 = np.arange(10)

In [64]:
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
array3 = array1[0:3]

In [66]:
array3

array([0, 1, 2])

In [67]:
array[:#]

SyntaxError: unexpected EOF while parsing (<ipython-input-67-35e51baaf253>, line 1)

In [68]:
array[:3]

NameError: name 'array' is not defined

In [69]:
array1[:3]

array([0, 1, 2])

In [70]:
array1[3:]

array([3, 4, 5, 6, 7, 8, 9])

In [71]:
array1[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
array3d = np.arange(start = 1, stop = 10).reshape(3, 3)

In [73]:
array3d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [74]:
array3d[:2, :2]

array([[1, 2],
       [4, 5]])

In [75]:
array3d[:2, :1]

array([[1],
       [4]])

In [76]:
array3d[1:, 2:]

array([[6],
       [9]])

In [77]:
array3 = array1d[array>5]

NameError: name 'array' is not defined

In [78]:
array1d = np.arange(10)

In [79]:
array3 = array1d[array1d>5]

In [80]:
array3

array([6, 7, 8, 9])

In [81]:
array1d>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [82]:
array1d==3

array([False, False, False,  True, False, False, False, False, False,
       False])

In [83]:
array1d>2 and array1d<8

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [84]:
a.any(array1d>2, array1d<3)

NameError: name 'a' is not defined

In [85]:
org_array = np.array([4, 2, 6, 1])

In [86]:
np.sort(org_array)

array([1, 2, 4, 6])

In [87]:
org_array.sort()

In [88]:
org_array

array([1, 2, 4, 6])

In [89]:
org_array[::-1]

array([6, 4, 2, 1])

In [90]:
array2d = np.array([[8, 12], [7, 1]])

In [91]:
array2d

array([[ 8, 12],
       [ 7,  1]])

In [1]:
np.sort(array2d, axis = 0)

NameError: name 'np' is not defined

In [2]:
import numpy as np


In [3]:
np.sort(array2d, axis = 0)

NameError: name 'array2d' is not defined

In [4]:
array2d = np.array([[8, 12], [7, 1]])

In [5]:
np.sort(array2d, axis = 0)

array([[ 7,  1],
       [ 8, 12]])

In [6]:
A = np.arange(start = 1, stop = 7).reshape(2, -1)

In [7]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
B = np.arange(start = 7, stop = 13).reshape(3, -1)

In [9]:
B


array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [10]:
A.dot(B)

array([[ 58,  64],
       [139, 154]])

In [11]:
np.transpose(A)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [12]:
A.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [13]:
import pandas as pd


In [14]:
pd

<module 'pandas' from '/Users/yunho/opt/anaconda3/lib/python3.8/site-packages/pandas/__init__.py'>

In [15]:
pd

<module 'pandas' from '/Users/yunho/opt/anaconda3/lib/python3.8/site-packages/pandas/__init__.py'>

In [16]:
a=3

In [17]:
a


3

In [18]:
titanic_df = pd.read_csv(r'/data/train.csv')

FileNotFoundError: [Errno 2] No such file or directory: '/data/train.csv'

In [19]:
titanic_df = pd.read_csv(r'data\train.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'data\\train.csv'

In [20]:
titanic_df = pd.read_csv(r'data/train.csv')

In [21]:
titanic_df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [22]:
titanic_df.head(3)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S

In [23]:
titanic_df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [24]:
titanic_df.shape

(891, 12)

In [25]:
type(titanic_df)

pandas.core.frame.DataFrame

In [26]:
titanic_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [27]:
titanic_df.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [28]:
import numpy as np



In [29]:
titanic_df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [30]:
dir(titanic_df)

['Age',
 'Cabin',
 'Embarked',
 'Fare',
 'Name',
 'Parch',
 'PassengerId',
 'Pclass',
 'Sex',
 'SibSp',
 'Survived',
 'T',
 'Ticket',
 '_AXIS_LEN',
 '_AXIS_NAMES',
 '_AXIS_NUMBERS',
 '_AXIS_ORDERS',
 '_AXIS_REVERSED',
 '_AXIS_TO_AXIS_NUMBER',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 

In [31]:
titanic_df.Age

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ... 
886    27.0
887    19.0
888     NaN
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [32]:
np.average

<function numpy.average(a, axis=None, weights=None, returned=False)>

In [33]:
np.average(np.array[1, 0, 3])

TypeError: 'builtin_function_or_method' object is not subscriptable

In [34]:
np.average(np.array([1, 0, 3]))

1.3333333333333333

In [ ]:
omega